image:
  pullPolicy: Never

config: |
  {
    "policies": [
      {
        "provider": "github",
        "id": "p1",
        "github": {
          "token": "test-ghtoken"
        },
        "userAuth": {
          "tokenHash": "test-usertokenhash"
        },
        "host": "test-nginx",
        "scheme": "http",
        "repositories": [
          {
            "name": "repo",
            "owner": "org",
            "project": "proj",
          },
          {
            "name": "repo%20space",
            "owner": "org",
            "project": "proj",
          }
        ]
      }
    ]
  }
