image:
  pullPolicy: Never

config: |
  {
    "policies": [
      {
        "provider": "github",
        "github": {
          "pat": "foobar"
        },
        "host": "test-nginx",
        "scheme": "http",
        "repositories": [
          {
            "name": "repo",
            "owner": "org",
            "project": "proj",
            "namespaces": ["tenant-1", "tenant-2"]
          },
          {
            "name": "repo%20space",
            "owner": "org",
            "project": "proj",
            "namespaces": ["tenant-1", "tenant-2"],
            "secretNameOverride": "foobar"
          }
        ]
      }
    ]
  }
