image:
  pullPolicy: Never

config: |
  {
    "organizations": [
      {
        "name": "org",
        "provider": "github",
        "github": {
          "pat": "foobar"
        },
        "host": "test-nginx",
        "scheme": "http",
        "repositories": [
          {
            "name": "repo"
          },
          {
            "name": "repo%20space",
            "secretNameOverride": "foobar"
          }
        ]
      }
    ]
  }
